//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatsApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CatsDBEntities : DbContext
    {
        public CatsDBEntities()
            : base("name=CatsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<ad> ad { get; set; }
        public virtual DbSet<breed> breed { get; set; }
        public virtual DbSet<pc_instance> pc_instance { get; set; }
        public virtual DbSet<personal_card> personal_card { get; set; }
        public virtual DbSet<pet> pet { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<vaccination_card> vaccination_card { get; set; }
        public virtual DbSet<vc_pc> vc_pc { get; set; }
    }
}
