//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal_card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personal_card()
        {
            this.pc_instance = new HashSet<pc_instance>();
            this.vc_pc = new HashSet<vc_pc>();
        }
    
        public int id { get; set; }
        public int petid { get; set; }
        public Nullable<int> age { get; set; }
        public int breedid { get; set; }
    
        public virtual breed breed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pc_instance> pc_instance { get; set; }
        public virtual pet pet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vc_pc> vc_pc { get; set; }
    }
}
