//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaccination_card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vaccination_card()
        {
            this.vc_pc = new HashSet<vc_pc>();
        }
    
        public int id { get; set; }
        public string vaccinename { get; set; }
        public Nullable<System.DateTime> vaccinedate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vc_pc> vc_pc { get; set; }
    }
}
